### ISSUE TITLE
Stopwatch not working.

### ISSUE THREAD

**Issue by Mxdi** [mathiasvr/tiny-timer#6]
timer = new Timer({ interval: 1000, stopwatch: true });

       timer.start();

       timer.on('tick', (ms) => { console.log(ms); });

1. It still requires a start time, 2. Even with a start time, doesnt do anything.

**Comment by leviathancodes** [comment]
Still experiencing this issue?  @Mxdi

**Comment by mathiasvr** [comment]
Hi, the `stopwatch` mode is a little odd because it requires you to call `.start(ms)` where `ms` is how long the stopwatch should run.

This was mostly to keep the source code simple and compatible with `countdown` mode.
I hope to extract the stopwatch functionality into its own file at some point, which also makes more sense in these days where you can perform tree-shaking if you don't need either mode.
